@startuml FacadePattern

package ComplexSubsystem #DDDDDD {
    class SubsystemA {
        + void subOperation()
    }

    class SubsystemB {
        + void subOperation()
    }

    class SubsystemC {
        + void subOperation()
    }
}

class Facade {
    __private member__
    - SubsystemA *ptr_a
    - SubsystemB *ptr_b
    - SubsystemC *ptr_c
    __public methods__
    + void operation_1()
    + void operation_2()
}

client ..> Facade : dependency
Facade --> SubsystemA : association
Facade --> SubsystemB : association
Facade --> SubsystemC : association

note as N1
    <b>Situation:</b>
    If Clients need to deal with many objects
    to complete the desired function, which makes
    system too complex.
    Add a new layer to encapsulate each object
    into a subsystem, then client depends on this
    new layer only... The changes in subsystem has
    NO impact on client.
end note

@enduml